namespace Altemiq.NetCore.Analyzers.Documentation;

using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;

public class GeneratedCodeDocumentationSuppressorTests
{
    [Test]
    [MethodDataSource(nameof(CSharp))]
    public async Task TestCSharp(string source, DiagnosticResult expected)
    {
        var testAnalyzer = new CSharpAnalyzerTest<GeneratedCodeDocumentationSuppressor, DefaultVerifier>
        {
            TestState =
            {
                Sources = { source },
#if NET10_0_OR_GREATER
                ReferenceAssemblies = ReferenceAssemblies.Net.Net100,
#elif NET9_0_OR_GREATER
                ReferenceAssemblies = ReferenceAssemblies.Net.Net90,
#else
                ReferenceAssemblies = ReferenceAssemblies.Net.Net80,
#endif
                AdditionalReferences = { Capacity = 0 },
            },
            CompilerDiagnostics = CompilerDiagnostics.All,
            ExpectedDiagnostics = { expected },
        };

        await testAnalyzer.RunAsync();
    }

    public static IEnumerable<Func<(string Source, DiagnosticResult DiagnosticResult)>> CSharp()
    {
        yield return () => (
            """
            // <autogenerated />

            namespace MyNamespace
            {
                public class UnDocumentedClass
                {
                }
            }
            """,
            new DiagnosticResult("CS1591", Microsoft.CodeAnalysis.DiagnosticSeverity.Warning)
                .WithLocation(5, 18)
                .WithIsSuppressed(true));
        yield return () => (
            """
            // <autogenerated/>

            namespace MyNamespace
            {
                public class UnDocumentedClass
                {
                }
            }
            """,
            new DiagnosticResult("CS1591", Microsoft.CodeAnalysis.DiagnosticSeverity.Warning)
                .WithLocation(5, 18)
                .WithIsSuppressed(true));
        yield return () => (
            """
            // <auto-generated />

            namespace MyNamespace
            {
                public class UnDocumentedClass
                {
                }
            }
            """,
            new DiagnosticResult("CS1591", Microsoft.CodeAnalysis.DiagnosticSeverity.Warning)
                .WithLocation(5, 18)
                .WithIsSuppressed(true));
        yield return () => (
            """
            // <auto-generated/>

            namespace MyNamespace
            {
                public class UnDocumentedClass
                {
                }
            }
            """,
            new DiagnosticResult("CS1591", Microsoft.CodeAnalysis.DiagnosticSeverity.Warning)
                .WithLocation(5, 18)
                .WithIsSuppressed(true));
        yield return () => (
            """
            namespace MyNamespace
            {
                public class UnDocumentedClass
                {
                }
            }
            """,
            new DiagnosticResult("CS1591", Microsoft.CodeAnalysis.DiagnosticSeverity.Warning)
                .WithLocation(3, 18));
    }
}