namespace Altemiq.NetCore.Analyzers.Documentation;

using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;

public class GeneratedCodeDocumentationSuppressorTests
{
    [Test]
    public async Task SuppressCS1591()
    {
        var testAnalyzer = new CSharpAnalyzerTest<GeneratedCodeDocumentationSuppressor, DefaultVerifier>
        {
            TestState =
            {
                Sources =
                {
                    """
                    // <autogenerated />

                    namespace MyNamespace
                    {
                        public class UnDocumentedClass
                        {
                        }
                    }
                    """,
                },
#if NET10_0_OR_GREATER
                ReferenceAssemblies = ReferenceAssemblies.Net.Net100,
#elif NET9_0_OR_GREATER
                ReferenceAssemblies = ReferenceAssemblies.Net.Net90,
#else
                ReferenceAssemblies = ReferenceAssemblies.Net.Net80,
#endif
                AdditionalReferences = { Capacity = 0 },
            },
            CompilerDiagnostics = CompilerDiagnostics.All,
            ExpectedDiagnostics =
            {
                new DiagnosticResult("CS1591", Microsoft.CodeAnalysis.DiagnosticSeverity.Warning)
                    .WithLocation(5, 18)
                    .WithIsSuppressed(true),
            },
        };

        await testAnalyzer.RunAsync();
    }
}