// -----------------------------------------------------------------------
// <copyright file="GeneratedCodeDocumentationSuppressor.cs" company="Altemiq">
// Copyright (c) Altemiq. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace Altemiq.NetCore.Analyzers.Documentation;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

/// <summary>
/// Suppresses analyzer for documentation when the code to auto generated.
/// </summary>
[DiagnosticAnalyzer(LanguageNames.CSharp, LanguageNames.VisualBasic)]
public class GeneratedCodeDocumentationSuppressor : DiagnosticSuppressor
{
    private static readonly SuppressionDescriptor SuppressDocumentationRule = new(
        id: "AS1591",
        suppressedDiagnosticId: "CS1591",
        justification: "Auto-generated code might not be documented, but should not break the build.");

    /// <inheritdoc/>
    public override System.Collections.Immutable.ImmutableArray<SuppressionDescriptor> SupportedSuppressions =>
        System.Collections.Immutable.ImmutableArray.Create(SuppressDocumentationRule);

    /// <inheritdoc/>
    public override void ReportSuppressions(SuppressionAnalysisContext context)
    {
        foreach (var diagnostic in context.ReportedDiagnostics
                     .Where(diagnostic => IsAutoGenerated(diagnostic.Location.SourceTree.GetRoot(context.CancellationToken))))
        {
            context.ReportSuppression(Suppression.Create(SuppressDocumentationRule, diagnostic));
        }

        static bool IsAutoGenerated(SyntaxNode node)
        {
            return HasGeneratedCodeAttribute(node) || HasAutoGeneratedHeader(node);

            static bool HasGeneratedCodeAttribute(SyntaxNode node)
            {
                return node
                    .DescendantNodes()
                    .Any(n => string.Equals(n.GetType().Name, "AttributeSyntax", StringComparison.Ordinal)
                              && n.ToString().Contains("GeneratedCode"));
            }

            static bool HasAutoGeneratedHeader(SyntaxNode node)
            {
                // allow for <auto-generated /> and <autogenerated />, and whether there is a leading space before />
                return node.GetLeadingTrivia().Any(trivia =>
                    trivia.ToString().Replace("-", string.Empty).Contains("<autogenerated"));
            }
        }
    }
}